import { useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { jsPDF } from 'jspdf';

const starterDocument = `#set page(paper: "a4", margin: (x: 2.4cm, y: 2.2cm))
#set text(font: "Libertinus Serif", size: 11pt)
#set par(justify: true, leading: 0.7em, first-line-indent: 1em)

#align(center)[
  #text(size: 19pt, weight: "bold")[
    A Fixed-Point Theorem for Contractive Maps
  ]
  #v(0.7em)
  #text(size: 11pt)[First Author · Department of Mathematics]
  #text(size: 10pt, style: "italic")[University Name · October 2026]
]

#v(1em)

== Abstract

We study the convergence of iterative processes generated by contractive maps on complete metric spaces. A concise proof of the fixed-point theorem is presented, followed by quantitative estimates for the rate of convergence. The final section discusses an elementary example and several directions for further work.

*Keywords:* fixed points, metric spaces, contraction mappings, iteration

= 1. Introduction

Mathematical research often begins with a simple question: what structure governs the objects under consideration? In this paper, we investigate this question for a class of maps whose repeated application brings points closer together.

The central idea is that a uniform contraction creates a stable location. Starting from any point, the sequence of iterates approaches this location. This phenomenon appears in numerical analysis, differential equations, optimization, and the theory of dynamical systems.

#quote[
  A small amount of structure can force a global conclusion.
]

#theorem[
  Let $X$ be a complete metric space and let $f: X -> X$ be a contraction. Then there exists a unique $x^* in X$ such that $f(x^*) = x^*$.
]

#proof[
  Since $f$ is a contraction, there exists $0 < c < 1$ such that $d(f(x), f(y)) <= c d(x, y)$ for all $x, y in X. Choose $x_0 in X$ and define $x_(n+1) = f(x_n)$.

  By induction, $d(x_(n+1), x_n) <= c^n d(x_1, x_0)$. Hence, for $m > n$, the sequence satisfies

  $
    d(x_m, x_n) <= d(x_1, x_0) sum_(k=n)^(m-1) c^k.
  $

  The right-hand side tends to zero as $n -> infinity$. Thus $(x_n)$ is Cauchy. Completeness gives a limit $x_n -> x^*$, and continuity implies $f(x^*) = x^*$.
]

#pagebreak()

= 2. Preliminaries

== Metric spaces

#definition[
  A metric space is a pair $(X,d)$ where $X$ is a set and $d: X times X -> RR$ satisfies, for all $x,y,z in X$, the properties $d(x,y) >= 0$, $d(x,y) = 0 <=> x = y$, $d(x,y) = d(y,x)$, and $d(x,z) <= d(x,y) + d(y,z)$.
]

The metric determines the geometry of the space. In particular, it gives meaning to convergence, continuity, and completeness. These notions are precisely what is required for the iterative argument above.

#lemma[
  Let $(x_n)$ converge to $x$ in a metric space. Then every subsequence $(x_(n_k))$ also converges to $x$.
]

#proof[
  Given $epsilon > 0$, choose $N$ such that $d(x_n,x) < epsilon$ whenever $n >= N$. Since $n_k -> infinity$, there exists $K$ such that $n_k >= N$ whenever $k >= K$. Therefore $d(x_(n_k),x) < epsilon$ for all $k >= K$.
]

== Quantitative convergence

#proposition[
  If $x_(n+1) = f(x_n)$ and $x^*$ is the fixed point, then $d(x_n,x^*) <= c^n d(x_0,x^*)$.
]

#proof[
  The contraction property gives $d(x_n,x^*) = d(f(x_(n-1)), f(x^*)) <= c d(x_(n-1),x^*)$. Iterating this inequality yields the claimed estimate.
]

The bound is useful because it converts a qualitative convergence result into a practical stopping criterion. To obtain an error below $epsilon$, it is enough to choose $n$ so that

$
  c^n d(x_0,x^*) < epsilon.
$

#pagebreak()

= 3. Examples and conclusions

== An affine map

Consider the function $f(x) = 1/2 x + 1$ on the real line. A fixed point satisfies

$
  x = 1/2 x + 1, quad x = 2.
$

Starting from $x_0 = 0$, the iteration becomes $x_(n+1) = 1/2 x_n + 1$. The first terms are

$
  x_0 = 0, quad x_1 = 1, quad x_2 = 3/2, quad x_3 = 7/4.
$

Thus the sequence approaches $2$ geometrically. The exact error is

$
  |x_n - 2| = 2^(-n+1).
$

== Discussion

The preceding sections demonstrate that the contraction assumption provides both existence and uniqueness of a fixed point. Moreover, the proof gives an explicit estimate on the rate at which the associated iteration converges.

The argument can be extended in several directions. One may replace the constant contraction factor by a variable sequence $(c_n)$ satisfying suitable summability conditions. Similar ideas also appear in Banach spaces, where the metric is induced by a norm.

#corollary[
  Under the assumptions above, the convergence of the iteration is geometric and independent of the initial point.
]

== Conclusion

We established the principal result and illustrated it with an elementary affine example. The central lesson is that completeness and a strict contraction are enough to transform local control into a global fixed point.

Several questions remain open. It would be interesting to determine which weaker regularity assumptions still guarantee convergence, and how the quantitative estimate changes for non-uniform contractions.

== References

- Banach, S. *Théorie des opérations linéaires*, 1922.
- Khamsi, M. A. and Kirk, W. *An Introduction to Metric Spaces and Fixed Point Theory*, 2001.`;

function inlineMarkup(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\*([^*]+)\*/g, '<strong>$1</strong>')
    .replace(/_([^_]+)_/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\$([^$]+)\$/g, '<span class="math-inline">$1</span>');
}

function collectBlock(lines, startIndex) {
  let depth = 0;
  const content = [];
  for (let index = startIndex; index < lines.length; index += 1) {
    const line = lines[index];
    depth += (line.match(/\[/g) || []).length - (line.match(/\]/g) || []).length;
    if (index === startIndex) content.push(line.slice(line.indexOf('[') + 1));
    else if (depth > 0) content.push(line);
    else {
      content.push(line.slice(0, line.lastIndexOf(']')));
      return { content, nextIndex: index + 1 };
    }
  }
  return { content, nextIndex: lines.length };
}

function renderContent(lines) {
  const output = [];
  let paragraph = [];
  let list = [];
  let math = [];
  let inMath = false;
  const flushParagraph = () => {
    if (paragraph.length) output.push(`<p>${inlineMarkup(paragraph.join(' '))}</p>`);
    paragraph = [];
  };
  const flushList = () => {
    if (list.length) output.push(`<ul>${list.map((item) => `<li>${inlineMarkup(item)}</li>`).join('')}</ul>`);
    list = [];
  };
  const flushMath = () => {
    if (math.length) output.push(`<div class="math-block">${inlineMarkup(math.join(' '))}</div>`);
    math = [];
  };

  lines.forEach((rawLine) => {
    const line = rawLine.trim();
    if (!line || line.startsWith('//')) {
      if (!inMath) { flushParagraph(); flushList(); }
      return;
    }
    if (line === '$') {
      if (inMath) flushMath();
      else { flushParagraph(); flushList(); }
      inMath = !inMath;
      return;
    }
    if (inMath) { math.push(line); return; }
    if (line.startsWith('= ')) {
      flushParagraph(); flushList(); output.push(`<h1>${inlineMarkup(line.slice(2))}</h1>`);
    } else if (line.startsWith('== ')) {
      flushParagraph(); flushList(); output.push(`<h2>${inlineMarkup(line.slice(3))}</h2>`);
    } else if (line.startsWith('- ')) {
      flushParagraph(); list.push(line.slice(2));
    } else if (line.startsWith('#')) {
      flushParagraph(); flushList();
    } else {
      paragraph.push(line);
    }
  });
  flushParagraph(); flushList(); flushMath();
  return output.join('');
}

function compileToPreview(source) {
  const lines = source.split('\n').map((line) => line.replace(/\s+\/\/.*$/, ''));
  const output = [];
  const labels = { theorem: 'Theorem', lemma: 'Lemma', proposition: 'Proposition', corollary: 'Corollary', definition: 'Definition', remark: 'Remark', proof: 'Proof' };
  for (let index = 0; index < lines.length;) {
    const line = lines[index].trim();
    if (!line || line.startsWith('//') || line.startsWith('#set ') || line.startsWith('#show ')
      || line.startsWith('#let ') || line.startsWith('#bibliography')) {
      index += 1;
      continue;
    }
    const match = line.match(/^#(theorem|lemma|proposition|corollary|definition|remark|proof|quote|align)\s*(?:\([^)]*\))?\[/);
    if (match) {
      const block = collectBlock(lines, index);
      const body = renderContent(block.content);
      if (labels[match[1]]) output.push(`<section class="typst-block ${match[1]}"><strong>${labels[match[1]]}.</strong>${body}</section>`);
      else if (match[1] === 'quote') output.push(`<blockquote>${body}</blockquote>`);
      else output.push(`<div class="aligned-content">${body}</div>`);
      index = block.nextIndex;
      continue;
    }
    if (line.startsWith('#pagebreak')) {
      output.push('<!--TYPO_PAGE_BREAK-->');
      index += 1;
      continue;
    }
    if (line.startsWith('#text(') || line.startsWith('#v(') || line.startsWith('#h(')) {
      index += 1;
      continue;
    }
    output.push(renderContent([line]));
    index += 1;
  }
  return output.join('').split('<!--TYPO_PAGE_BREAK-->').map((page, pageIndex) => (
    `<section class="paper-page"><div class="paper-page-content">${page}</div><span class="paper-page-number">${pageIndex + 1}</span></section>`
  )).join('');
}

export default function TypstEditor() {
  const [source, setSource] = useState(starterDocument);
  const [fileName, setFileName] = useState('main.typ');
  const [saved, setSaved] = useState(false);
  const [zoom, setZoom] = useState(100);
  const [editorWidth, setEditorWidth] = useState(50);
  const lineNumbersRef = useRef(null);
  const preview = useMemo(() => compileToPreview(source), [source]);
  const lineCount = source.split('\n').length;
  const pageCount = Math.max(1, (source.match(/#pagebreak\s*\(/g) || []).length + 1);

  const saveDocument = () => {
    localStorage.setItem('typst-document', source);
    setSaved(true);
    window.setTimeout(() => setSaved(false), 1800);
  };

  const exportPdf = () => {
    const documentTitle = fileName.replace(/\.typ$/i, '') || 'document';
    const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 22;
    let y = 27;

    pdf.setTextColor(42, 41, 57);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(22);
    pdf.text(documentTitle, margin, y);
    y += 12;
    pdf.setDrawColor(224, 224, 235);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 10;
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(11);

    const printableLines = source
      .split('\n')
      .filter((line) => !line.trim().startsWith('#set ') && !line.trim().startsWith('#let '))

    printableLines.forEach((line) => {
      const trimmedLine = line.trim();
      if (!trimmedLine) {
        y += 4;
        return;
      }
      if (trimmedLine.startsWith('= ')) {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(20);
        line = trimmedLine.slice(2);
      } else if (trimmedLine.startsWith('== ')) {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(14);
        line = trimmedLine.slice(3);
      } else {
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(11);
      }

      const wrappedLines = pdf.splitTextToSize(line, pageWidth - (margin * 2));
      wrappedLines.forEach((wrappedLine) => {
        if (y > pageHeight - margin) {
          pdf.addPage();
          y = margin;
        }
        pdf.text(wrappedLine, margin, y);
        y += 6;
      });
      y += 2;
    });

    pdf.save(`${documentTitle}.pdf`);
  };

  const resizePanels = (event) => {
    event.preventDefault();
    const workspace = event.currentTarget.parentElement;
    const updateWidth = (moveEvent) => {
      const bounds = workspace.getBoundingClientRect();
      const nextWidth = ((moveEvent.clientX - bounds.left) / bounds.width) * 100;
      setEditorWidth(Math.min(68, Math.max(32, nextWidth)));
    };
    const stopResize = () => {
      window.removeEventListener('pointermove', updateWidth);
      window.removeEventListener('pointerup', stopResize);
    };
    window.addEventListener('pointermove', updateWidth);
    window.addEventListener('pointerup', stopResize);
  };

  return (
    <main className="editor-app">
      <header className="topbar">
        <div className="brand">
          <div className="brand-mark">T</div>
          <span>Typst<span className="brand-muted">er</span></span>
          <span className="beta-pill">BETA</span>
        </div>
        <div className="topbar-actions">
          <span className="saved-status">{saved ? 'Saved locally' : 'Unsaved changes'}</span>
          <button className="icon-button" onClick={saveDocument} title="Save document">↧</button>
          <Link className="files-link" to="/files">All files</Link>
          <button className="export-button" onClick={exportPdf}>Export PDF</button>
          <div className="avatar">Y</div>
        </div>
      </header>

      <div className="workspace" style={{ gridTemplateColumns: `${editorWidth}% 8px minmax(0, 1fr)` }}>
        <section className="editor-pane">
          <div className="pane-toolbar">
            <div className="document-title"><input value={fileName} onChange={(event) => setFileName(event.target.value)} /><span className="edit-pencil">✎</span></div>
            <div className="editor-tools"><span>UTF-8</span><span>Spaces: 2</span><button className="run-button">▶ Run</button></div>
          </div>
          <div className="code-area">
            <div className="line-numbers" ref={lineNumbersRef} aria-hidden="true">{Array.from({ length: lineCount }, (_, index) => <span key={index}>{index + 1}</span>)}</div>
            <textarea
              aria-label="Typst source editor"
              spellCheck="false"
              value={source}
              onChange={(event) => setSource(event.target.value)}
              onScroll={(event) => {
                if (lineNumbersRef.current) lineNumbersRef.current.scrollTop = event.currentTarget.scrollTop;
              }}
            />
          </div>
          <div className="statusbar"><span className="status-dot" /> <span>Compiled successfully</span><span className="status-spacer" /><span>Ln {lineCount}, Col 1</span><span>Typst</span></div>
        </section>

        <button className="resize-handle" aria-label="Resize editor and preview panels" onPointerDown={resizePanels}><span /></button>
        <section className="preview-pane">
          <div className="pane-toolbar preview-toolbar"><div className="preview-heading"><span className="preview-icon">◩</span> Preview <span className="page-count">· {pageCount} pages</span></div><div className="preview-tools"><button onClick={() => setZoom((value) => Math.max(70, value - 10))}>−</button><span>{zoom}%</span><button onClick={() => setZoom((value) => Math.min(130, value + 10))}>+</button><span className="toolbar-divider" /><button title="Fit to page" onClick={() => setZoom(100)}>Fit</button></div></div>
          <div className="preview-canvas"><div className="preview-stage"><div className="paper-zoom" style={{ zoom: zoom / 100 }}><div className="paper-stack" dangerouslySetInnerHTML={{ __html: preview }} /></div></div></div>
          <div className="preview-status"><span className="status-dot" /> Preview is up to date <span>•</span> Updated just now</div>
        </section>
      </div>
    </main>
  );
}
